# Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.
algo = input("Digite algo: ")
print(f"O tipo primitivo de {algo} é {type(algo).__name__}")
print(f"Só tem espaços? {algo.isspace()}")
print(f"É alfanumérico? {algo.isalnum()}")
print(f"É alfabético? {algo.isalpha()}")
print(f"É numérico? {algo.isnumeric()}")
print(f"Está em maiúsculas? {algo.isupper()}")
print(f"Está em minúsculas? {algo.islower()}")
print(f"Está capitalizado? {algo.istitle()}")   
